### ISSUE TITLE
I can‘t use ref in the vue^3.3.4and vite^4.4.5

### ISSUE THREAD

**Issue by nightmare-mio** [antfu/vitesse#512] opened 2023-11-05 13:15 UTC
### Describe the bug

# this's my package.json
![image](https://github.com/antfu/vitesse/assets/52735303/ba1fd01c-dc09-470c-8ad0-c395c4a9eb07)
# this's a new project,without config
![image](https://github.com/antfu/vitesse/assets/52735303/6183862f-752b-4487-87ae-8b3d9b05a2ec)
# this's new project，"Helloworld" can operate normally,but ref can't
![image](https://github.com/antfu/vitesse/assets/52735303/bbaa7d03-781a-42f6-b448-0c469f1975f5)
![image](https://github.com/antfu/vitesse/assets/52735303/06be6021-4672-478b-810d-9353cc680462)

### Reproduction

no

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 7.46 GB / 23.84 GB
  Binaries:
    Node: 20.3.1 - D:\environment\node-v20.3.1-win-x64\node.EXE
    Yarn: 1.22.19 - D:\environment\node-v20.3.1-win-x64\yarn.CMD
    npm: 9.6.7 - D:\environment\node-v20.3.1-win-x64\npm.CMD
    pnpm: 8.8.0 - D:\environment\node-v20.3.1-win-x64\pnpm.CMD
  Browsers:
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ares-Chang** [comment] 2023-11-08 06:49
Please refer to [unplugin-auto-import](https://github.com/unplugin/unplugin-auto-import#readme), which can refer to APIs automatically.

This project has been configured with plugins so you don't have to actively reference them

Otherwise, quote 'ref' proactively

```ts
import { computed, ref } from 'vue'

const count = ref(0)
const doubled = computed(() => count.value * 2)
```

**Comment by antfu** [comment] 2023-11-09 01:34
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-11-09 01:34 UTC
