### ISSUE TITLE
Use Pinia local code to change the value, but there is no hot update

### ISSUE THREAD

**Issue by wsw2000** [antfu/vitesse#347] opened 2022-05-06 02:51 UTC

**Comment by antfu** [comment] 2022-05-06 03:05
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-06 03:05 UTC
