### ISSUE TITLE
POST method or any other http method for static pages

### ISSUE THREAD

**Issue by u007** [antfu/vitesse#353] opened 2022-05-09 06:04 UTC
**Describe the bug/issue**

hi,

ive a running website with vitesses. works fine. but when i attempt to post to any of the pages url  via curl, it return 403 bad request (empty)

on netlify it return 404.

how do i allow other http method like POST or PUT for my page to work like GET ?
do i need to change something in the route?

**Comment by antfu** [comment] 2022-05-09 06:06
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed** 2022-05-09 06:06 UTC

**Comment by u007** [comment] 2022-05-09 06:07
hi, 
the starter page itself is the example

**Comment by flapili** [comment] 2022-05-24 14:58
@u007 vitesse is not a webserver or an http api, it's just a boilerplate around vite-ssg, which build html files.
There is no reason to do a post on the dev server of vite or the netlify's servers.

look like you need an api ? if it's the case this is out of scope of vitesse or either vue ecosystem

**Comment by u007** [comment] 2022-05-26 08:54
@flapili okay thank you, i did a workaround on server api to redirect to vitesse project

**Comment by spokospace** [comment] 2022-05-26 14:26
^ if it's not extra big database u can try with data in json file. I'm using vitesse in this way :)

**Comment by u007** [comment] 2022-05-27 15:12
ohh no, i needed to receive post from a postback from payment gateway
