### ISSUE TITLE
error on npm install due to invalid vueuse/head version

### ISSUE THREAD

**Issue by mariusa** [antfu/vitesse#265] opened 2021-12-30 21:03 UTC
https://github.com/antfu/vitesse/blob/cf503587e7aff7c046dcee2eba16a47ad90ec99d/package.json#L16

The latest is 0.2.3, not 0.7
https://github.com/vueuse/head/blob/main/package.json

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @vueuse/head@0.7.4
npm ERR! node_modules/@vueuse/head
npm ERR!   @vueuse/head@"^0.7.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @vueuse/head@"^0.5.1" from vite-ssg@0.17.2
npm ERR! node_modules/vite-ssg
npm ERR!   dev vite-ssg@"^0.17.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Comment by hannoeru** [comment] 2021-12-31 23:11
The latest version is 0.7.4, that is just packge.json not up-to-date with npm version.
https://www.npmjs.com/package/@vueuse/head

Duplicate of #219

**Closed by hannoeru** 2021-12-31 23:11 UTC
