### ISSUE TITLE
Uncaught ReferenceError: App is not defined

### ISSUE THREAD

**Issue by ArgekarStudios** [antfu/vitesse#220] opened 2021-10-26 10:42 UTC
What is the use of APp.vue here since it's pointing to index.vue/

and we are getting error at import App from './App.vue'
cannot find a module

**Comment by antfu** [comment] 2021-11-02 01:51
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2021-11-02 01:51 UTC

**Comment by riderx** [comment] 2021-11-08 13:43
I have the same issue in vscode 
<img width="1138" alt="Screenshot 2021-11-08 at 13 42 33" src="https://user-images.githubusercontent.com/4084527/140752352-97d7f637-97bb-48f3-9eb7-29c57e7a7129.png">

**Comment by riderx** [comment] 2021-11-08 13:56
i fixed the issue by using volar take over mode

**Comment by arbassic** [comment] 2021-11-23 13:37
Also you can put in the `shims.d.ts` file followin declaration

```typescript
declare module '*.vue' {
  import { Component } from 'vue'
  export default { Component }
}
```
