### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by titandiaz** [antfu/vitesse#398] opened 2022-08-05 08:33 UTC
### Describe the bug

Don't finish production build: 
[vite-ssg] Build for server...

This line of code generates a build error: 
```vue
<dd class="flex">
     <i i="heroicons-outline-phone" class="flex-shrink-0 h-6 w-6 text-gray-400" />
     <span class="ml-3"> text </span>
 </dd>
```

### Full template

```vue
<template>
  <div id="contact" class="qtx-form relative bg-white">
    <div class="absolute inset-0">
      <div class="absolute inset-y-0 left-0 w-1/2 bg-gray-50" />
    </div>
    <div class="relative max-w-7xl mx-auto lg:grid lg:grid-cols-5">
      <div class="bg-gray-50 py-16 px-4 sm:px-6 lg:col-span-2 lg:px-8 lg:py-24 xl:pr-12">
        <div class="max-w-lg mx-auto">
          <h2 class="text-2xl font-extrabold tracking-tight text-gray-900 sm:text-3xl">
            Contacto
          </h2>
          <p class="mt-3 text-lg leading-6 text-gray-500">
            Nullam risus blandit ac aliquam justo ipsum. Quam mauris volutpat massa dictumst amet. Sapien tortor lacus arcu.
          </p>
          <dl class="mt-8 text-base text-gray-500">
            <div>
              <dt class="sr-only">
                Postal address
              </dt>
              <dd>
                <p>Carrera 20 # 36-04</p>
                <p>Yopal, Casanare - Colombia</p>
              </dd>
            </div>

            <div class="mt-6">
              <dt class="sr-only">
                Phone number
              </dt>
              <dd class="flex">
                <i i="heroicons-outline-phone" class="flex-shrink-0 h-6 w-6 text-gray-400" />
                <span class="ml-3"> text </span>
              </dd>
            </div>
            <div class="mt-3">
              <dt class="sr-only">
                Email
              </dt>
              <dd class="flex">
                <i i="heroicons-outline-mail" class="flex-shrink-0 h-6 w-6 text-gray-400" />
                <span class="ml-3"> relacionamiento@cataruben.org </span>
              </dd>
            </div>
          </dl>
        </div>
      </div>

      <div class="bg-white py-16 px-4 sm:px-6 lg:col-span-3 lg:py-24 lg:px-8 xl:pl-12">
        <div class="max-w-lg mx-auto lg:max-w-none">
          <FormKit
            type="form" :actions="false" :incomplete-message="false" @submit="sendContactInformation"
          >
            <FormKit
              type="text"
              name="name"
              label="Nombre"
              placeholder="Nombre completo"
              validation="required|length:4"
            />
            <FormKit
              type="email"
              name="email"
              label="Correo"
              placeholder="Correo"
              validation="required|email"
            />
            <FormKit
              type="text"
              name="subject"
              label="Celular"
              placeholder="Celular"
              validation="required|number|length:10,10"
            />
            <FormKit
              type="textarea"
              name="message"
              label="Mensaje"
              placeholder="Mensaje"
              validation="required|length:20"
              rows="4"
            />
            <div>
              <button type="submit" class="btn-brick">
                Enviar
              </button>
            </div>
          </FormKit>
        </div>
      </div>
    </div>
  </div>
</template>
```
### Reproduction

<dd class="flex">
          <i i="heroicons-outline-phone" class="flex-shrink-0 h-6 w-6 text-gray-400" />
         <span class="ml-3"> text </span>
</dd>

### System Info

```Shell
OS: macOS Monterey
Version: 12.2.1

MacBook Air (M1, 2020)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-08-06 16:00
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-06 16:00 UTC
